### PR TITLE
Add Plank theme

### PR DESCRIPTION
**Pull request by vyvir**
I borrowed the Plank file from https://github.com/darkomarko42/Marwaita-manjaro.
I think it looks pretty good and fits the theme quite well.
If possible, please turn on the "Issues" tab. Thank you.

### CODE REVIEW

**Comment by tfpf** [comment]
Please add the licence file from [darkomarko42/Marwaita-manjaro](https://github.com/darkomarko42/Marwaita-manjaro) too. You can create it at `Teal-Sea-Light/plank/COPYING` or `Teal-Sea-Light/plank/LICENSE`. Give me a few days to review this; I don't have my Xfce machine with me right now.

**Comment by vyvir** [comment]
Added the license.

**Comment by tfpf** [comment]
You're right, it matches the theme well!

**Comment by tfpf** [comment]
I have enabled issues in this repository, but cannot guarantee I'll be able to address them in time. I had developed this theme when I was college and had a lot free time to tinker around with GTK tools. Recently, I moved to a system with a HiDPI display, and found this theme lacking (window scaling makes it work beautifully, though), but could never get around to fix it or create a HiDPI version. Hence the cessation of development.🙂

**Pull request merged**
